### PR TITLE
U16: Create missing unknown vein, eye art

### PR DESCRIPTION
**Pull request by Croxsy**
Added the hidden veins and the activity tile. Hope you like it:)

### CODE REVIEW

**Review by Patertuck — APPROVED** [review]
Beautiful!

**Comment by Twhining** [comment]
looks great!

**Comment by paul891112** [comment]
Looks amazing, thanks for your great work!

**Review by paul891112 — APPROVED** [review]

**Review by C0DECYCLE — APPROVED** [review]
Love it! Good work

**Pull request merged**
