### PR TITLE
U16: Create UI Inventory Background and Final Buttons

### PR DESCRIPTION
**Pull request by Croxsy**
I added the final buttons and the background to the tiles. Both have the same style. 

We really need to find a font that looks good ->I think for lobby screen we should use a pixel font but then for the game maybe leave it

Ah and i also already added the buttons for Leon's PR hope that doesn't give any conflicts

### CODE REVIEW

**Review by Patertuck — COMMENTED** [review]
They look very nice! What about the start and share buttons? 🤔

**Comment by Croxsy** [comment]
> They look very nice! What about the start and share buttons? 🤔

lol they didn't get pushed I guess. They are now also in the PR

**Review by Patertuck — APPROVED** [review]
Looks great. @Twhining should be able to easily rebase his code onto this one with the new assets.
Regarding the font: Am absolutely down, want to talk about it on tuesday?

**Review by paul891112 — APPROVED** [review]
Again amazing art, really appreciate your effort! 👍

**Review by C0DECYCLE — APPROVED** [review]
Super! Thanks @Croxsy

**Pull request merged**
